# page 45

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x = tf.linspace(10.0, 12.0, 3)
print(x)

Tensor("LinSpace:0", shape=(3,), dtype=float32)


In [3]:
y = tf.range(3, 18, 3)
z = tf.range(5)

In [4]:
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y))
    print(sess.run(z))
sess.close()

[10. 11. 12.]
[ 3  6  9 12 15]
[0 1 2 3 4]


# page 52 Placeholders

In [5]:
a = tf.placeholder(tf.float32, shape=[3])

In [6]:
b = tf.constant([5.,5.,5.])
c = a+b

In [7]:
with tf.Session() as sess:
    print(sess.run(c,feed_dict={a: [1.,2.,3.]}))

[6. 7. 8.]


In [8]:
x = tf.placeholder(tf.float32, shape=[1024,1024])
y = tf.matmul(x,x)

In [9]:
with tf.Session() as sess:
    feed = np.random.rand(1024,1024)
    print(sess.run(y,feed_dict={x: feed}))

[[248.05313 247.93175 239.69058 ... 255.00385 247.38512 237.15224]
 [252.99075 260.6057  244.36967 ... 264.94293 258.82318 242.59515]
 [254.69933 256.36517 250.54916 ... 260.1112  262.05582 250.61806]
 ...
 [266.12347 264.704   250.7899  ... 270.09195 265.7172  252.86926]
 [249.42032 250.8327  237.36842 ... 255.5405  255.7554  238.53824]
 [254.1805  257.51105 245.35995 ... 259.1139  255.37129 244.37991]]


### Tensorflow feed 실행 예시 
Session은 feed 일 경우는 feed_dict으로 처리 값을 할당해야 함


In [10]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [11]:
x = tf.add(a,b)
y = tf.multiply(a,b)

In [12]:
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(x, feed_dict={a: 2.5, b: 3.5}))
    print(sess.run(y, feed_dict={a: 5.0, b: 1.7}))


6.0
8.5


# page 58 출력 포맷 지정하기


In [13]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

bias = tf.Variable(1.0)

Instructions for updating:
Colocations handled automatically by placer.


In [14]:
y_pred = x**2 + bias

loas = (y-y_pred)**2

In [15]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print('Loss(x,y)=%16.8f' % sess.run(loas, feed_dict={x: 3.0, y: 5}))
    print('pred_y(x)=%16.8f' % sess.run(y_pred, feed_dict={x: 3.0}))
    print('bias     =%16.8f' % sess.run(bias))

Loss(x,y)=     25.00000000
pred_y(x)=     10.00000000
bias     =      1.00000000
